### PR TITLE
Feature1 checked

### PR DESCRIPTION
**Pull request by klong15**

### CODE REVIEW

**Comment by klong15** [comment]
Only Team A is on here. Both emails should get this message.

**Comment by klong15** [comment]
N altalt is on here. Since the setting is enabled, only altalt should get the email.

**Comment by klong15** [comment]
Fuck, both are still getting the email...

**Comment by klong15** [comment]
Now a team is removed... lets see what happens now

**Review by klongaltalt — COMMENTED** [review]
What is this??

**Comment by klong15** [comment]
I dunno

**Comment by klongaltalt** [comment]
gah

**Pull request closed without merging**
